name: mistralai/Mistral-7B-Instruct-v0.2
type: CausalLM
epochs: 1
per_device_batch_size: 1
real_batch_size: 32
bf16: True
eval_epochs: 1
early_stopping_patience: 3
max_length: 1024
logging_steps: 1
learning_rate: 1e-4
weight_decay: 0.0
prec_reg: 1e-6
saving: false
warmup_ratio: 0.03
warmup_steps: 0
lr_scheduler_type: cosine